import 'package:mad_1_gamenova_1/core/game.dart';

final List<Game> dGames = [
  Game(
    id: 12,
    name: 'Wolfenstein II: The New Colossus',
    type: "Digital",
    genre: "Shooter",
    duration: 22,
    platform: "PC",
    price: 3500,
    releasedDate: "2017-10-27",
    ageRating: 18,
    size: 55,
    description: "Fight Nazis in an alternate-history America",
    image: 'assets/images/products/digital/Wolfenstein II The New Colossus.jpeg',
    company: "MachineGames",
  ),

  Game(
    id: 13,
    name: 'Project CARS 3',
    type: "Digital",
    genre: "Car",
    duration: 16,
    platform: "PS4",
    price: 3700,
    releasedDate: "2020-08-28",
    ageRating: 3,
    size: 42,
    description: "Realistic racing game with deep customization",
    image: 'assets/images/products/digital/Project CARS 3.jpeg',
    company: "Slightly Mad Studios",
  ),

  Game(
    id: 14,
    name: 'Divinity: Original Sin 2',
    type: "Digital",
    genre: "RPG",
    duration: 95,
    platform: "PC",
    price: 4600,
    releasedDate: "2017-09-14",
    ageRating: 17,
    size: 60,
    description: "Turn-based fantasy RPG with co-op support",
    image: 'assets/images/products/digital/Divinity Original Sin 2.jpg',
    company: "Larian Studios",
  ),

  Game(
    id: 15,
    name: 'Metro Exodus',
    type: "Digital",
    genre: "Shooter",
    duration: 30,
    platform: "PC",
    price: 4000,
    releasedDate: "2019-02-15",
    ageRating: 18,
    size: 59,
    description: "Post-apocalyptic FPS with survival elements",
    image: 'assets/images/products/digital/Metro Exodus.jpeg',
    company: "4A Games",
  ),

  Game(
    id: 16,
    name: 'WRC 10',
    type: "Digital",
    genre: "Car",
    duration: 12,
    platform: "PC",
    price: 3300,
    releasedDate: "2021-09-02",
    ageRating: 3,
    size: 34,
    description: "Official FIA rally racing simulation",
    image: 'assets/images/products/digital/WRC 10.jpeg',
    company: "KT Racing",
  ),

  Game(
    id: 17,
    name: 'Persona 5 Royal',
    type: "Digital",
    genre: "RPG",
    duration: 110,
    platform: "PS4",
    price: 5200,
    releasedDate: "2020-03-31",
    ageRating: 16,
    size: 45,
    description: "Stylish turn-based RPG with life simulation",
    image: 'assets/images/products/digital/Persona 5 Royal.jpeg',
    company: "Atlus",
  ),

  Game(
    id: 18,
    name: 'Titanfall 2',
    type: "Digital",
    genre: "Shooter",
    duration: 20,
    platform: "PC",
    price: 2800,
    releasedDate: "2016-10-28",
    ageRating: 16,
    size: 48,
    description: "Pilot titans in fast-paced mech FPS action",
    image: 'assets/images/products/digital/titanfall 2.jpeg',
    company: "Respawn Entertainment",
  ),

  Game(
    id: 19,
    name: 'The Crew 2',
    type: "Digital",
    genre: "Car",
    duration: 15,
    platform: "XBOX",
    price: 3400,
    releasedDate: "2018-06-29",
    ageRating: 12,
    size: 38,
    description: "Open-world racing across land, air, and sea",
    image: 'assets/images/products/digital/The Crew 2.jpeg',
    company: "Ivory Tower",
  ),

  Game(
    id: 20,
    name: 'Nioh 2 – The Complete Edition',
    type: "Digital",
    genre: "RPG",
    duration: 85,
    platform: "PC",
    price: 4400,
    releasedDate: "2021-02-05",
    ageRating: 18,
    size: 75,
    description: "Challenging samurai action RPG with yokai",
    image: 'assets/images/products/digital/Nioh 2.webp',
    company: "Team Ninja",
  ),

  Game(
    id: 21,
    name: 'Assassins Creed IV: Black Flag',
    type: "Digital",
    genre: "RPG",
    duration: 60,
    platform: "PC",
    price: 3600,
    releasedDate: "2013-10-29",
    ageRating: 18,
    size: 30,
    description: "Pirate-themed open-world RPG with naval battles",
    image: 'assets/images/products/digital/Assassins Creed IV Black Flag.jpeg',
    company: "Ubisoft",
  ),
];
