import 'package:mad_1_gamenova_1/core/game.dart';

final List<Game> pGames = [
  Game(
    id: 1,
    name: 'The Witcher 3: Wild Hunt',
    type: "Physical",
    genre: "RPG",
    duration: 60,
    platform: "XBOX",
    price: 1400,
    releasedDate: "2014-01-11",
    ageRating: 15,
    size: 30,
    description: "A well know RPG game",
    image: 'assets/images/products/physical/witcher3.jpeg',
    company: "CDPR",
  ),

  Game(
    id: 2,
    name: 'Call of Duty: Modern Warfare II',
    type: "Physical",
    genre: "Shooter",
    duration: 25,
    platform: "PS5",
    price: 4500,
    releasedDate: "2022-10-28",
    ageRating: 18,
    size: 70,
    description: "A modern military FPS with fast-paced action",
    image: 'assets/images/products/physical/Call of Duty - Modern Warfare II.jpeg',
    company: "Infinity Ward",
  ),

  Game(
    id: 3,
    name: 'Gran Turismo 7',
    type: "Physical",
    genre: "Car",
    duration: 15,
    platform: "PS5",
    price: 5000,
    releasedDate: "2022-03-04",
    ageRating: 3,
    size: 90,
    description: "Realistic racing simulator with hundreds of cars",
    image: 'assets/images/products/physical/Gran Turismo 7.jpg',
    company: "Polyphony Digital",
  ),

  Game(
    id: 4,
    name: 'The Elder Scrolls V: Skyrim',
    type: "Physical",
    genre: "RPG",
    duration: 120,
    platform: "PC",
    price: 2800,
    releasedDate: "2011-11-11",
    ageRating: 17,
    size: 12,
    description: "Open-world fantasy RPG with dragons and magic",
    image: 'assets/images/products/physical/Skyrim.jpeg',
    company: "Bethesda",
  ),

  Game(
    id: 5,
    name: 'Forza Horizon 5',
    type: "Physical",
    genre: "Car",
    duration: 20,
    platform: "XBOX",
    price: 4200,
    releasedDate: "2021-11-09",
    ageRating: 3,
    size: 103,
    description: "Open-world racing across Mexico",
    image: 'assets/images/products/physical/Forza Horizon 5.jpeg',
    company: "Playground Games",
  ),

  Game(
    id: 6,
    name: 'Red Dead Redemption 2',
    type: "Physical",
    genre: "RPG",
    duration: 100,
    platform: "PS4",
    price: 3500,
    releasedDate: "2018-10-26",
    ageRating: 18,
    size: 105,
    description: "Epic western RPG with immersive storytelling",
    image: 'assets/images/products/physical/Red Dead Redemption 2.jpg',
    company: "Rockstar Games",
  ),

  Game(
    id: 7,
    name: 'Battlefield 2042',
    type: "Physical",
    genre: "Shooter",
    duration: 30,
    platform: "XBOX",
    price: 3900,
    releasedDate: "2021-11-19",
    ageRating: 18,
    size: 70,
    description: "Multiplayer-focused futuristic warfare shooter",
    image: 'assets/images/products/physical/Battlefield 2042.webp',
    company: "DICE",
  ),

  Game(
    id: 8,
    name: 'Cyberpunk 2077',
    type: "Physical",
    genre: "RPG",
    duration: 80,
    platform: "PC",
    price: 4000,
    releasedDate: "2020-12-10",
    ageRating: 18,
    size: 70,
    description: "Open-world RPG set in a dystopian future",
    image: 'assets/images/products/physical/Cyberpunk-2077.jpg',
    company: "CD Projekt",
  ),

  Game(
    id: 9,
    name: 'Doom Eternal',
    type: "Physical",
    genre: "Shooter",
    duration: 20,
    platform: "PS4",
    price: 3000,
    releasedDate: "2020-03-20",
    ageRating: 18,
    size: 40,
    description: "Fast-paced demon-slaying FPS action",
    image: 'assets/images/products/physical/Doom Eternal.jpeg',
    company: "id Software",
  ),

  Game(
    id: 10,
    name: 'Need for Speed Heat',
    type: "Physical",
    genre: "Car",
    duration: 12,
    platform: "PC",
    price: 3200,
    releasedDate: "2019-11-08",
    ageRating: 12,
    size: 50,
    description: "Street racing in day-night cycles",
    image: 'assets/images/products/physical/nfs heat.webp',
    company: "Ghost Games",
  ),

  Game(
    id: 11,
    name: 'Mass Effect Legendary Edition',
    type: "Physical",
    genre: "RPG",
    duration: 90,
    platform: "XBOX",
    price: 4600,
    releasedDate: "2021-05-14",
    ageRating: 17,
    size: 120,
    description: "Remastered sci-fi RPG trilogy",
    image: 'assets/images/products/physical/Mass Effect.jpg',
    company: "BioWare",
  ),
];
